server:
  listen: 8000
  workers: 4

  upstreams:
    - id: jsonplaceholder
      url: jsonplaceholder.typicode.com

    - id: users
      url: jsonplaceholder.typicode.com

    - id: posts
      url: jsonplaceholder.typicode.com

    - id: comments
      url: jsonplaceholder.typicode.com

    - id: fallingfalling
      url: papertoilet.com

  headers:
    - name: x-forwarded-for
      value: "$ip"

    - name: Authorization
      value: "zain"

  rules:
    - path: "^/todos$"  # Exact match
      upstream:  
        - jsonplaceholder
      
    - path: "^/posts(?:/\\d+)?$"  # Matches /posts and /posts/123
      upstream:  
        - posts
    
    - path: "^/comments(?:/\\d+)?$"  # Matches /comments and /comments/99
      upstream:  
        - comments
    
    - path: "^/users/(\\d+)/comments$"  # Matches /users/42/comments
      upstream:  
        - users
    
    - path: "^/$"
      static_file: proxy-guide.html 
